Хочу обсудить
Во сколько вы оценили бы эту задачу (время и деньги)? Расскажите про свои условия сотрудничества
Если мы определимся со стилистикой на первой странице, ускорит ли это разработку следующих страниц?
Как будет устроен процесс работы над задачей? 
Будете ли вы заниматься передачей и приемкой задачи у разработки?
Как будет устроен процесс передачи в разработку?
Как будет устроен процесс приемки?
Что конкретно вы передадите в разработку по этой задаче?
Есть ли договор?
Как будет происходить оплата?
Кто будет проводить анализ?
Сколько будет вариантов?

Готов созвониться, если так будет удобнее. 


* TODO Получить от Татьяны форму Доверенности
* TODO Получить от Татьяны подпись для окна со ставкой, что-то типа «Нажимая на кнопку «Подтвердить заявку» вы соглашаетесь с формой Договора-заявки»
* TODO Оформить доработку с договором заявкой при ставке через ЛК
* TODO Глянуть описание для маркетов
* TODO Доработать форму авторизации
* TODO Добавление нового водителя описать задачу (уделить внимание верификации)
* TODO доделать ТН
* TODO Доработать верификацию компаний (подгрузку сделать обязательным полем)
* TODO Описать движение мильной партии по статусам в ЛМС